### ISSUE TITLE
moving tags on already shared bitrise step

### ISSUE THREAD

**Issue by godrei** [adrianchinghc/bitrise-step-appcenter-codepush-release-react-native#3]
Hi, it seems you share the step's `0.0.1` version with the state: `bdbfa011fc1469fd2cb583f3cc732cfc01e013b8`, but later you moved the tag `0.0.1` to another commit: `d40d779d1ad4ed160257f5ae4bfadde6f37cad42`.

This way the step version points to another state of the code base which is not allowed in bitrise steps. Please put the tag back to its original commit: `bdbfa011fc1469fd2cb583f3cc732cfc01e013b8`.

**Comment by adrianchinghc** [comment]
Hi @godrei Apologies for the delay. Was away. I've moved the tag `0.0.1` back to the commit `bdbfa011fc1469fd2cb583f3cc732cfc01e013b8 `

**Comment by godrei** [comment]
Thanks @adrianchinghc ,
the steplib builds are running fine.
