### ISSUE TITLE
Description flag doesn't work

### ISSUE THREAD

**Issue by marioot** [adrianchinghc/bitrise-step-appcenter-codepush-release-react-native#4]
When trying to add a description in the extra options field and using the envirronment variable:
ie:
--description $BITRISE_GIT_MESSAGE

Where the BITRISE_GIT_MESSAGE is:
"This is a description"

The produced command looks like:
appcenter codepush release-react -a XXX/App --token [REDACTED] --quiet --description '"This' is a 'description"' --deployment-name Staging

**Comment by adrianchinghc** [comment]
@marioot Thanks for reporting. I created a PR (#5) to add option for description. Can you test that out and let me know if it works?
